"""Add wholesale_start_quantity to product

Revision ID: 007300d55563
Revises: ddd633084a41
Create Date: 2025-07-20 14:52:52.020568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007300d55563'
down_revision: Union[str, Sequence[str], None] = 'ddd633084a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('wholesale_start_quantity', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'wholesale_start_quantity')
    # ### end Alembic commands ###
