"""Update orders model

Revision ID: 0f784d6cbc6b
Revises: 0aa631cd4429
Create Date: 2026-04-15 20:06:12.200335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0f784d6cbc6b'
down_revision: Union[str, Sequence[str], None] = '0aa631cd4429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
delivery_types_enum = postgresql.ENUM('pickup', 'courier', name='delivery_types')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    delivery_types_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('orders', sa.Column('delivery_type', delivery_types_enum, nullable=False))
    op.alter_column('orders', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('orders', 'delivery_type')
    delivery_types_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
