"""update orders table with user

Revision ID: 40cc0d0cc612
Revises: 7b34567057d3
Create Date: 2026-03-02 22:40:25.139374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '40cc0d0cc612'
down_revision: Union[str, Sequence[str], None] = '7b34567057d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


order_status_enum = postgresql.ENUM(
    'pending',
    'confirmed',
    'shipped',
    'delivered',
    'cancelled',
    name='order_status',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('orders', sa.Column('user_uid', sa.String(), nullable=False))

    # explicitly create PostgreSQL ENUM type before using it in the column
    order_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'orders',
        sa.Column(
            'status',
            order_status_enum,
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
    )
    op.create_foreign_key(None, 'orders', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'user_uid')

    # drop ENUM type after the column has been removed
    order_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
