"""Add rating trigger

Revision ID: 419463d3fbd5
Revises: 9d1da004835e
Create Date: 2025-07-16 18:48:55.532301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419463d3fbd5'
down_revision: Union[str, Sequence[str], None] = '9d1da004835e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    op.execute("""
    CREATE OR REPLACE FUNCTION update_product_avg_rating()
    RETURNS TRIGGER AS $$
    DECLARE
      prod_id VARCHAR(8);
    BEGIN
      prod_id := COALESCE(NEW.product_id, OLD.product_id);

      UPDATE products
      SET rating = COALESCE((
        SELECT AVG(rating)
        FROM feedbacks
        WHERE product_id = prod_id
      ), NULL)
      WHERE id = prod_id;

      RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;
    """)

    # AFTER INSERT
    op.execute("""
    CREATE TRIGGER trg_feedback_insert
    AFTER INSERT ON feedbacks
    FOR EACH ROW
    EXECUTE FUNCTION update_product_avg_rating();
    """)

    # AFTER UPDATE (только если рейтинг изменился)
    op.execute("""
    CREATE TRIGGER trg_feedback_update
    AFTER UPDATE ON feedbacks
    FOR EACH ROW
    WHEN (OLD.rating IS DISTINCT FROM NEW.rating)
    EXECUTE FUNCTION update_product_avg_rating();
    """)

    # AFTER DELETE
    op.execute("""
    CREATE TRIGGER trg_feedback_delete
    AFTER DELETE ON feedbacks
    FOR EACH ROW
    EXECUTE FUNCTION update_product_avg_rating();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'rating')
    op.alter_column('categories', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###

    op.execute("DROP TRIGGER IF EXISTS trg_feedback_insert ON feedbacks;")
    op.execute("DROP TRIGGER IF EXISTS trg_feedback_update ON feedbacks;")
    op.execute("DROP TRIGGER IF EXISTS trg_feedback_delete ON feedbacks;")
    op.execute("DROP FUNCTION IF EXISTS update_product_avg_rating;")