"""change product unit type

Revision ID: 68e5e97279b0
Revises: d0334a7e85c3
Create Date: 2025-08-30 16:58:05.803754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68e5e97279b0'
down_revision: Union[str, Sequence[str], None] = 'd0334a7e85c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'unit',
               existing_type=postgresql.ENUM('кг', 'шт', name='unit'),
               type_=sa.String(),
               existing_nullable=False,
               server_default="кг")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'unit', server_default=None)
    op.alter_column(
        'products',
        'unit',
        type_=postgresql.ENUM('кг', 'шт', name='unit'),
        existing_type=sa.String(),
        postgresql_using="unit::unit",
        existing_nullable=False
    )
    # ### end Alembic commands ###
