"""update orders table: add city field

Revision ID: 8b7cdc0c3952
Revises: 40cc0d0cc612
Create Date: 2026-03-02 22:56:39.375683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7cdc0c3952'
down_revision: Union[str, Sequence[str], None] = '40cc0d0cc612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('city', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'city')
    # ### end Alembic commands ###
