"""Add products table

Revision ID: ab7ac74c5a90
Revises: 9a76cc41c74a
Create Date: 2025-07-15 13:55:53.914066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7ac74c5a90'
down_revision: Union[str, Sequence[str], None] = '9a76cc41c74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=8), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('кг', 'шт', name='unit'), nullable=False),
    sa.Column('stock', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('default', 'new', 'sale', name='status'), server_default=sa.text("'default'"), nullable=False),
    sa.Column('order_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_vendors',
    sa.Column('product_id', sa.String(length=8), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'vendor_id')
    )
    op.alter_column('feedbacks', 'product_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=False)
    op.create_foreign_key(None, 'feedbacks', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.alter_column('feedbacks', 'product_id',
               existing_type=sa.String(length=8),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_table('product_vendors')
    op.drop_table('products')
    # ### end Alembic commands ###
