"""update orders table: add uuid primary key

Revision ID: b582e6175ca8
Revises: 8b7cdc0c3952
Create Date: 2026-03-03 18:49:55.833134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b582e6175ca8'
down_revision: Union[str, Sequence[str], None] = '8b7cdc0c3952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.drop_constraint(op.f('orders_user_uid_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.alter_column('orders', 'id', server_default=None)

    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="gen_random_uuid()",
               server_default=sa.text("gen_random_uuid()"))
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="gen_random_uuid()",)
    op.add_column('orders', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('address', sa.Text(), nullable=True))


    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['uid'])
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'user_uid')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE EXTENSION IF EXISTS pgcrypto")
    op.add_column('orders', sa.Column('user_uid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('delivery_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_uid_fkey'), 'orders', 'users', ['user_uid'], ['uid'])
    op.alter_column('orders', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'user_id')
    op.alter_column('order_items', 'order_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###