"""Add wholesale price

Revision ID: b8e596ea38c6
Revises: 419463d3fbd5
Create Date: 2025-07-16 19:02:45.749110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e596ea38c6'
down_revision: Union[str, Sequence[str], None] = '419463d3fbd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('wholesale_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###
    # Update existing products
    op.execute("UPDATE products SET wholesale_price = 0.0")

    # Make wholesale_price non-nullable
    op.alter_column("products", "wholesale_price", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'wholesale_price')
    # ### end Alembic commands ###
